[
  {
    spotId: 1,
    spotName: 'a1',
    groupId: 1,
    groupName: '달리셔스1',
    zipCode: '12345',
    address1: '서울 강남구 역삼로 168',
    address2: '팁스타운S6',
    location: null,
    diningType: '아침, 점심, 저녁',
    breakfastLastOrderTime: '00:00',
    breakfastDeliveryTime: '08:00',
    breakfastUseDays: '월, 수, 금, 화, 목',
    breakfastSupportPrice: 5000,
    lunchLastOrderTime: '09:00',
    lunchDeliveryTime: '12:00',
    lunchUseDays: '월, 수, 금, 화, 목',
    lunchSupportPrice: 6000,
    dinnerLastOrderTime: '15:00',
    dinnerDeliveryTime: '18:00',
    dinnerUseDays: '월, 수, 금, 화, 목',
    dinnerSupportPrice: 7000,
    createdDateTime: '2023-02-14',
    updatedDateTime: '2023-03-02',
  },
  {
    spotId: 2,
    spotName: 'a2',
    groupId: 1,
    groupName: '달리셔스1',
    zipCode: '12345',
    address1: '서울 강남구 역삼로 168',
    address2: '팁스타운S6',
    location: null,
    diningType: '아침, 점심, 저녁',
    breakfastLastOrderTime: '00:00',
    breakfastDeliveryTime: '08:00',
    breakfastUseDays: '월, 수, 금, 화, 목',
    breakfastSupportPrice: 5000,
    lunchLastOrderTime: '09:00',
    lunchDeliveryTime: '12:00',
    lunchUseDays: '월, 수, 금, 화, 목',
    lunchSupportPrice: 6000,
    dinnerLastOrderTime: '15:00',
    dinnerDeliveryTime: '18:00',
    dinnerUseDays: '월, 수, 금, 화, 목',
    dinnerSupportPrice: 7000,
    createdDateTime: '2023-02-14',
    updatedDateTime: '2023-03-02',
  },
  {
    spotId: 3,
    spotName: 'a3',
    groupId: 1,
    groupName: '달리셔스1',
    zipCode: '12345',
    address1: '서울 강남구 역삼로 168',
    address2: '팁스타운S6',
    location: null,
    diningType: '아침, 점심, 저녁',
    breakfastLastOrderTime: '00:00',
    breakfastDeliveryTime: '08:00',
    breakfastUseDays: '월, 수, 금, 화, 목',
    breakfastSupportPrice: 5000,
    lunchLastOrderTime: '09:00',
    lunchDeliveryTime: '12:00',
    lunchUseDays: '월, 수, 금, 화, 목',
    lunchSupportPrice: 6000,
    dinnerLastOrderTime: '15:00',
    dinnerDeliveryTime: '18:00',
    dinnerUseDays: '월, 수, 금, 화, 목',
    dinnerSupportPrice: 7000,
    createdDateTime: '2023-02-14',
    updatedDateTime: '2023-03-02',
  },
  {
    spotId: 4,
    spotName: 'a4',
    groupId: 2,
    groupName: '위시티자이아파트',
    zipCode: '10323',
    address1: '경기도 고양시 일산동구 식사동',
    address2: '위시티 4로 45',
    location: null,
    diningType: '아침, 점심, 저녁',
    breakfastLastOrderTime: '05:00',
    breakfastDeliveryTime: '08:00',
    breakfastUseDays: '월, 화, 수, 목, 금',
    breakfastSupportPrice: null,
    lunchLastOrderTime: '09:00',
    lunchDeliveryTime: '12:00',
    lunchUseDays: '월, 화, 수, 목, 금',
    lunchSupportPrice: null,
    dinnerLastOrderTime: '15:00',
    dinnerDeliveryTime: '18:00',
    dinnerUseDays: '월, 화, 수, 목, 금',
    dinnerSupportPrice: null,
    createdDateTime: '2023-02-14',
    updatedDateTime: '2023-03-02',
  },
  {
    spotId: 5,
    spotName: 'a5',
    groupId: 2,
    groupName: '위시티자이아파트',
    zipCode: '10323',
    address1: '경기도 고양시 일산동구 식사동',
    address2: '위시티 4로 45',
    location: null,
    diningType: '아침, 점심, 저녁',
    breakfastLastOrderTime: '05:00',
    breakfastDeliveryTime: '08:00',
    breakfastUseDays: '월, 화, 수, 목, 금',
    breakfastSupportPrice: null,
    lunchLastOrderTime: '09:00',
    lunchDeliveryTime: '12:00',
    lunchUseDays: '월, 화, 수, 목, 금',
    lunchSupportPrice: null,
    dinnerLastOrderTime: '15:00',
    dinnerDeliveryTime: '18:00',
    dinnerUseDays: '월, 화, 수, 목, 금',
    dinnerSupportPrice: null,
    createdDateTime: '2023-02-14',
    updatedDateTime: '2023-03-02',
  },
  {
    spotId: 6,
    spotName: 'a6',
    groupId: 2,
    groupName: '위시티자이아파트',
    zipCode: '10323',
    address1: '경기도 고양시 일산동구 식사동',
    address2: '위시티 4로 45',
    location: null,
    diningType: '아침, 점심, 저녁',
    breakfastLastOrderTime: '05:00',
    breakfastDeliveryTime: '08:00',
    breakfastUseDays: '월, 화, 수, 목, 금',
    breakfastSupportPrice: null,
    lunchLastOrderTime: '09:00',
    lunchDeliveryTime: '12:00',
    lunchUseDays: '월, 화, 수, 목, 금',
    lunchSupportPrice: null,
    dinnerLastOrderTime: '15:00',
    dinnerDeliveryTime: '18:00',
    dinnerUseDays: '월, 화, 수, 목, 금',
    dinnerSupportPrice: null,
    createdDateTime: '2023-02-14',
    updatedDateTime: '2023-03-02',
  },
  {
    spotId: 7,
    spotName: 'a7',
    groupId: 3,
    groupName: '밀당PT 여의도',
    zipCode: '7335',
    address1: '서울특별시 영등포구 여의대로 108',
    address2: '파크원',
    location: null,
    diningType: '점심, 저녁, 아침',
    breakfastLastOrderTime: '05:00',
    breakfastDeliveryTime: '08:00',
    breakfastUseDays: '월, 화, 수, 목, 금',
    breakfastSupportPrice: 7000,
    lunchLastOrderTime: '00:00',
    lunchDeliveryTime: '08:00',
    lunchUseDays: '월, 화, 수, 목, 금',
    lunchSupportPrice: 10000,
    dinnerLastOrderTime: '09:00',
    dinnerDeliveryTime: '12:00',
    dinnerUseDays: '월, 화, 수, 목, 금',
    dinnerSupportPrice: 0,
    createdDateTime: '2023-02-22',
    updatedDateTime: '2023-03-02',
  },
  {
    spotId: 8,
    spotName: 'a8',
    groupId: 3,
    groupName: '밀당PT 여의도',
    zipCode: '7335',
    address1: '서울특별시 영등포구 여의대로 108',
    address2: '파크원',
    location: null,
    diningType: '점심, 저녁, 아침',
    breakfastLastOrderTime: '05:00',
    breakfastDeliveryTime: '08:00',
    breakfastUseDays: '월, 화, 수, 목, 금',
    breakfastSupportPrice: 7000,
    lunchLastOrderTime: '00:00',
    lunchDeliveryTime: '08:00',
    lunchUseDays: '월, 화, 수, 목, 금',
    lunchSupportPrice: 10000,
    dinnerLastOrderTime: '09:00',
    dinnerDeliveryTime: '12:00',
    dinnerUseDays: '월, 화, 수, 목, 금',
    dinnerSupportPrice: 0,
    createdDateTime: '2023-02-22',
    updatedDateTime: '2023-03-02',
  },
  {
    spotId: 10,
    spotName: 'a9',
    groupId: 1,
    groupName: '달리셔스1',
    zipCode: '12345',
    address1: '서울 강남구 역삼로 168',
    address2: '팁스타운S6',
    location: null,
    diningType: '아침, 점심, 저녁',
    breakfastLastOrderTime: '09:00',
    breakfastDeliveryTime: '09:00',
    breakfastUseDays: '월, 화, 수, 목, 금',
    breakfastSupportPrice: null,
    lunchLastOrderTime: '09:00',
    lunchDeliveryTime: '09:00',
    lunchUseDays: '월, 화, 수, 목, 금',
    lunchSupportPrice: null,
    dinnerLastOrderTime: '15:00',
    dinnerDeliveryTime: '18:00',
    dinnerUseDays: '월, 화, 수, 목, 금',
    dinnerSupportPrice: null,
    createdDateTime: '2023-03-01',
    updatedDateTime: '2023-03-02',
  },
  {
    spotId: 11,
    spotName: 'a10',
    groupId: 1,
    groupName: '달리셔스1',
    zipCode: '12345',
    address1: '서울 강남구 역삼로 168',
    address2: '팁스타운S6',
    location: null,
    diningType: '아침, 점심, 저녁',
    breakfastLastOrderTime: '09:00',
    breakfastDeliveryTime: '09:00',
    breakfastUseDays: '월, 화, 수, 목, 금',
    breakfastSupportPrice: null,
    lunchLastOrderTime: '09:00',
    lunchDeliveryTime: '09:00',
    lunchUseDays: '월, 화, 수, 목, 금',
    lunchSupportPrice: null,
    dinnerLastOrderTime: '15:00',
    dinnerDeliveryTime: '18:00',
    dinnerUseDays: '월, 화, 수, 목, 금',
    dinnerSupportPrice: null,
    createdDateTime: '2023-03-01',
    updatedDateTime: '2023-03-02',
  },
  {
    spotId: 13,
    spotName: 'a11',
    groupId: 1,
    groupName: '달리셔스1',
    zipCode: '12345',
    address1: '서울 강남구 역삼로 168',
    address2: '팁스타운S6',
    location: null,
    diningType: '아침, 점심, 저녁',
    breakfastLastOrderTime: '09:00',
    breakfastDeliveryTime: '09:00',
    breakfastUseDays: '월, 화, 수, 목, 금',
    breakfastSupportPrice: null,
    lunchLastOrderTime: '09:00',
    lunchDeliveryTime: '09:00',
    lunchUseDays: '월, 화, 수, 목, 금',
    lunchSupportPrice: null,
    dinnerLastOrderTime: '15:00',
    dinnerDeliveryTime: '18:00',
    dinnerUseDays: '월, 화, 수, 목, 금',
    dinnerSupportPrice: null,
    createdDateTime: '2023-03-01',
    updatedDateTime: '2023-03-02',
  },
  {
    spotId: 14,
    spotName: 'a12',
    groupId: 2,
    groupName: '위시티자이아파트',
    zipCode: '10323',
    address1: '경기도 고양시 일산동구 식사동',
    address2: '위시티 4로 45',
    location: null,
    diningType: '아침, 점심, 저녁',
    breakfastLastOrderTime: '09:00',
    breakfastDeliveryTime: '09:00',
    breakfastUseDays: '월, 화, 수, 목, 금',
    breakfastSupportPrice: null,
    lunchLastOrderTime: '09:00',
    lunchDeliveryTime: '09:00',
    lunchUseDays: '월, 화, 수, 목, 금',
    lunchSupportPrice: null,
    dinnerLastOrderTime: '15:00',
    dinnerDeliveryTime: '18:00',
    dinnerUseDays: '월, 화, 수, 목, 금',
    dinnerSupportPrice: null,
    createdDateTime: '2023-03-01',
    updatedDateTime: '2023-03-02',
  },
  {
    spotId: 17,
    spotName: 'a13',
    groupId: 3,
    groupName: '밀당PT 여의도',
    zipCode: '7335',
    address1: '서울특별시 영등포구 여의대로 108',
    address2: '파크원',
    location: null,
    diningType: '아침, 점심, 저녁',
    breakfastLastOrderTime: '09:00',
    breakfastDeliveryTime: '09:00',
    breakfastUseDays: '월, 화, 수, 목, 금',
    breakfastSupportPrice: null,
    lunchLastOrderTime: '09:00',
    lunchDeliveryTime: '09:00',
    lunchUseDays: '월, 화, 수, 목, 금',
    lunchSupportPrice: null,
    dinnerLastOrderTime: '15:00',
    dinnerDeliveryTime: '18:00',
    dinnerUseDays: '월, 화, 수, 목, 금',
    dinnerSupportPrice: null,
    createdDateTime: '2023-03-01',
    updatedDateTime: '2023-03-02',
  },
  {
    spotId: 21,
    spotName: 'a14',
    groupId: 1,
    groupName: '달리셔스1',
    zipCode: '12345',
    address1: '서울 강남구 역삼로 168',
    address2: '팁스타운S6',
    location: null,
    diningType: '아침, 점심, 저녁',
    breakfastLastOrderTime: '09:00',
    breakfastDeliveryTime: '09:00',
    breakfastUseDays: '월, 화, 수, 목, 금',
    breakfastSupportPrice: null,
    lunchLastOrderTime: '09:00',
    lunchDeliveryTime: '09:00',
    lunchUseDays: '월, 화, 수, 목, 금',
    lunchSupportPrice: null,
    dinnerLastOrderTime: '15:00',
    dinnerDeliveryTime: '18:00',
    dinnerUseDays: '월, 화, 수, 목, 금',
    dinnerSupportPrice: null,
    createdDateTime: '2023-03-01',
    updatedDateTime: '2023-03-02',
  },
  {
    spotId: 22,
    spotName: 'a15',
    groupId: 1,
    groupName: '달리셔스1',
    zipCode: '12345',
    address1: '서울 강남구 역삼로 168',
    address2: '팁스타운S6',
    location: null,
    diningType: '아침, 점심, 저녁',
    breakfastLastOrderTime: '09:00',
    breakfastDeliveryTime: '09:00',
    breakfastUseDays: '월, 화, 수, 목, 금',
    breakfastSupportPrice: null,
    lunchLastOrderTime: '09:00',
    lunchDeliveryTime: '09:00',
    lunchUseDays: '월, 화, 수, 목, 금',
    lunchSupportPrice: null,
    dinnerLastOrderTime: '15:00',
    dinnerDeliveryTime: '18:00',
    dinnerUseDays: '월, 화, 수, 목, 금',
    dinnerSupportPrice: null,
    createdDateTime: '2023-03-01',
    updatedDateTime: '2023-03-02',
  },
  {
    spotId: 23,
    spotName: 'a16',
    groupId: 1,
    groupName: '달리셔스1',
    zipCode: '12345',
    address1: '서울 강남구 역삼로 168',
    address2: '팁스타운S6',
    location: null,
    diningType: '아침, 점심, 저녁',
    breakfastLastOrderTime: '09:00',
    breakfastDeliveryTime: '09:00',
    breakfastUseDays: '월, 화, 수, 목, 금',
    breakfastSupportPrice: null,
    lunchLastOrderTime: '09:00',
    lunchDeliveryTime: '09:00',
    lunchUseDays: '월, 화, 수, 목, 금',
    lunchSupportPrice: null,
    dinnerLastOrderTime: '15:00',
    dinnerDeliveryTime: '18:00',
    dinnerUseDays: '월, 화, 수, 목, 금',
    dinnerSupportPrice: null,
    createdDateTime: '2023-03-01',
    updatedDateTime: '2023-03-02',
  },
  {
    spotId: 24,
    spotName: 'a17',
    groupId: 1,
    groupName: '달리셔스1',
    zipCode: '12345',
    address1: '서울 강남구 역삼로 168',
    address2: '팁스타운S6',
    location: null,
    diningType: '아침, 점심, 저녁',
    breakfastLastOrderTime: '09:00',
    breakfastDeliveryTime: '09:00',
    breakfastUseDays: '월, 화, 수, 목, 금',
    breakfastSupportPrice: null,
    lunchLastOrderTime: '09:00',
    lunchDeliveryTime: '09:00',
    lunchUseDays: '월, 화, 수, 목, 금',
    lunchSupportPrice: null,
    dinnerLastOrderTime: '15:00',
    dinnerDeliveryTime: '18:00',
    dinnerUseDays: '월, 화, 수, 목, 금',
    dinnerSupportPrice: null,
    createdDateTime: '2023-03-01',
    updatedDateTime: '2023-03-02',
  },
  {
    spotId: 25,
    spotName: 'a18',
    groupId: 1,
    groupName: '달리셔스1',
    zipCode: '12345',
    address1: '서울 강남구 역삼로 168',
    address2: '팁스타운S6',
    location: null,
    diningType: '아침, 점심, 저녁',
    breakfastLastOrderTime: '09:00',
    breakfastDeliveryTime: '09:00',
    breakfastUseDays: '월, 화, 수, 목, 금',
    breakfastSupportPrice: null,
    lunchLastOrderTime: '09:00',
    lunchDeliveryTime: '09:00',
    lunchUseDays: '월, 화, 수, 목, 금',
    lunchSupportPrice: null,
    dinnerLastOrderTime: '15:00',
    dinnerDeliveryTime: '18:00',
    dinnerUseDays: '월, 화, 수, 목, 금',
    dinnerSupportPrice: null,
    createdDateTime: '2023-03-01',
    updatedDateTime: '2023-03-02',
  },
  {
    spotId: 26,
    spotName: 'a19',
    groupId: 1,
    groupName: '달리셔스1',
    zipCode: '12345',
    address1: '서울 강남구 역삼로 168',
    address2: '팁스타운S6',
    location: null,
    diningType: '아침, 점심, 저녁',
    breakfastLastOrderTime: '09:00',
    breakfastDeliveryTime: '09:00',
    breakfastUseDays: '월, 화, 수, 목, 금',
    breakfastSupportPrice: null,
    lunchLastOrderTime: '09:00',
    lunchDeliveryTime: '09:00',
    lunchUseDays: '월, 화, 수, 목, 금',
    lunchSupportPrice: null,
    dinnerLastOrderTime: '15:00',
    dinnerDeliveryTime: '18:00',
    dinnerUseDays: '월, 화, 수, 목, 금',
    dinnerSupportPrice: null,
    createdDateTime: '2023-03-01',
    updatedDateTime: '2023-03-02',
  },
  {
    spotId: 27,
    spotName: 'a20',
    groupId: 1,
    groupName: '달리셔스1',
    zipCode: '12345',
    address1: '서울 강남구 역삼로 168',
    address2: '팁스타운S6',
    location: null,
    diningType: '아침, 점심, 저녁',
    breakfastLastOrderTime: '09:00',
    breakfastDeliveryTime: '09:00',
    breakfastUseDays: '월, 화, 수, 목, 금',
    breakfastSupportPrice: null,
    lunchLastOrderTime: '09:00',
    lunchDeliveryTime: '09:00',
    lunchUseDays: '월, 화, 수, 목, 금',
    lunchSupportPrice: null,
    dinnerLastOrderTime: '15:00',
    dinnerDeliveryTime: '18:00',
    dinnerUseDays: '월, 화, 수, 목, 금',
    dinnerSupportPrice: null,
    createdDateTime: '2023-03-01',
    updatedDateTime: '2023-03-02',
  },
  {
    spotId: 28,
    spotName: 'a21',
    groupId: 1,
    groupName: '달리셔스1',
    zipCode: '12345',
    address1: '서울 강남구 역삼로 168',
    address2: '팁스타운S6',
    location: null,
    diningType: '아침, 점심, 저녁',
    breakfastLastOrderTime: '00:00',
    breakfastDeliveryTime: '08:00',
    breakfastUseDays: '월,화,수,목,금',
    breakfastSupportPrice: 5000,
    lunchLastOrderTime: '09:00',
    lunchDeliveryTime: '12:00',
    lunchUseDays: '월,화,수,목,금',
    lunchSupportPrice: 5000,
    dinnerLastOrderTime: '15:00',
    dinnerDeliveryTime: '18:00',
    dinnerUseDays: '월,화,수,목,금',
    dinnerSupportPrice: 5000,
    createdDateTime: '2023-03-01',
    updatedDateTime: '2023-03-02',
  },
  {
    spotId: 29,
    spotName: 'a22',
    groupId: 1,
    groupName: '달리셔스1',
    zipCode: '12345',
    address1: '서울 강남구 역삼로 168',
    address2: '팁스타운S6',
    location: null,
    diningType: '아침, 점심, 저녁',
    breakfastLastOrderTime: '09:00',
    breakfastDeliveryTime: '09:00',
    breakfastUseDays: '월, 화, 수, 목, 금',
    breakfastSupportPrice: null,
    lunchLastOrderTime: '09:00',
    lunchDeliveryTime: '09:00',
    lunchUseDays: '월, 화, 수, 목, 금',
    lunchSupportPrice: null,
    dinnerLastOrderTime: '09:00',
    dinnerDeliveryTime: '09:00',
    dinnerUseDays: '월, 화, 수, 목, 금',
    dinnerSupportPrice: null,
    createdDateTime: '2023-03-01',
    updatedDateTime: '2023-03-02',
  },
  {
    spotId: 30,
    spotName: 'a23',
    groupId: 1,
    groupName: '달리셔스1',
    zipCode: '12345',
    address1: '서울 강남구 역삼로 168',
    address2: '팁스타운S6',
    location: null,
    diningType: '아침, 점심, 저녁',
    breakfastLastOrderTime: '00:00',
    breakfastDeliveryTime: '09:00',
    breakfastUseDays: '월, 화, 수, 목, 금',
    breakfastSupportPrice: null,
    lunchLastOrderTime: '00:00',
    lunchDeliveryTime: '09:00',
    lunchUseDays: '월, 화, 수, 목, 금',
    lunchSupportPrice: null,
    dinnerLastOrderTime: '00:00',
    dinnerDeliveryTime: '09:00',
    dinnerUseDays: '월, 화, 수, 목, 금',
    dinnerSupportPrice: null,
    createdDateTime: '2023-03-01',
    updatedDateTime: '2023-03-02',
  },
  {
    spotId: 31,
    spotName: 'a24',
    groupId: 1,
    groupName: '달리셔스1',
    zipCode: '12345',
    address1: '서울 강남구 역삼로 168',
    address2: '팁스타운S6',
    location: null,
    diningType: '아침, 점심, 저녁',
    breakfastLastOrderTime: '00:00',
    breakfastDeliveryTime: '00:00',
    breakfastUseDays: '월, 화, 수, 목, 금',
    breakfastSupportPrice: null,
    lunchLastOrderTime: '00:00',
    lunchDeliveryTime: '00:00',
    lunchUseDays: '월, 화, 수, 목, 금',
    lunchSupportPrice: null,
    dinnerLastOrderTime: '00:00',
    dinnerDeliveryTime: '00:00',
    dinnerUseDays: '월, 화, 수, 목, 금',
    dinnerSupportPrice: null,
    createdDateTime: '2023-03-01',
    updatedDateTime: '2023-03-02',
  },
  {
    spotId: 32,
    spotName: 'a25',
    groupId: 1,
    groupName: '달리셔스1',
    zipCode: '12345',
    address1: '서울 강남구 역삼로 168',
    address2: '팁스타운S6',
    location: null,
    diningType: '아침, 점심, 저녁',
    breakfastLastOrderTime: '00:00',
    breakfastDeliveryTime: '00:00',
    breakfastUseDays: '월, 화, 수, 목, 금',
    breakfastSupportPrice: null,
    lunchLastOrderTime: '00:00',
    lunchDeliveryTime: '00:00',
    lunchUseDays: '월, 화, 수, 목, 금',
    lunchSupportPrice: null,
    dinnerLastOrderTime: '00:00',
    dinnerDeliveryTime: '00:00',
    dinnerUseDays: '월, 화, 수, 목, 금',
    dinnerSupportPrice: null,
    createdDateTime: '2023-03-01',
    updatedDateTime: '2023-03-02',
  },
  {
    spotId: 33,
    spotName: 'a26',
    groupId: 1,
    groupName: '달리셔스1',
    zipCode: '12345',
    address1: '서울 강남구 역삼로 168',
    address2: '팁스타운S6',
    location: null,
    diningType: '아침, 점심, 저녁',
    breakfastLastOrderTime: '00:00',
    breakfastDeliveryTime: '00:00',
    breakfastUseDays: '월, 화, 수, 목, 금',
    breakfastSupportPrice: null,
    lunchLastOrderTime: '00:00',
    lunchDeliveryTime: '00:00',
    lunchUseDays: '월, 화, 수, 목, 금',
    lunchSupportPrice: null,
    dinnerLastOrderTime: '00:00',
    dinnerDeliveryTime: '00:00',
    dinnerUseDays: '월, 화, 수, 목, 금',
    dinnerSupportPrice: null,
    createdDateTime: '2023-03-01',
    updatedDateTime: '2023-03-02',
  },
  {
    spotId: 34,
    spotName: 'a27',
    groupId: 1,
    groupName: '달리셔스1',
    zipCode: '12345',
    address1: '서울 강남구 역삼로 168',
    address2: '팁스타운S6',
    location: null,
    diningType: '아침, 점심, 저녁',
    breakfastLastOrderTime: '00:00',
    breakfastDeliveryTime: '00:00',
    breakfastUseDays: '월, 화, 수, 목, 금',
    breakfastSupportPrice: null,
    lunchLastOrderTime: '00:00',
    lunchDeliveryTime: '00:00',
    lunchUseDays: '월, 화, 수, 목, 금',
    lunchSupportPrice: null,
    dinnerLastOrderTime: '00:00',
    dinnerDeliveryTime: '00:00',
    dinnerUseDays: '월, 화, 수, 목, 금',
    dinnerSupportPrice: null,
    createdDateTime: '2023-03-01',
    updatedDateTime: '2023-03-02',
  },
  {
    spotId: 35,
    spotName: 'a28',
    groupId: 1,
    groupName: '달리셔스1',
    zipCode: '12345',
    address1: '서울 강남구 역삼로 168',
    address2: '팁스타운S6',
    location: null,
    diningType: '아침, 점심, 저녁',
    breakfastLastOrderTime: '00:00',
    breakfastDeliveryTime: '00:00',
    breakfastUseDays: '월, 화, 수, 목, 금',
    breakfastSupportPrice: null,
    lunchLastOrderTime: '00:00',
    lunchDeliveryTime: '00:00',
    lunchUseDays: '월, 화, 수, 목, 금',
    lunchSupportPrice: null,
    dinnerLastOrderTime: '00:00',
    dinnerDeliveryTime: '00:00',
    dinnerUseDays: '월, 화, 수, 목, 금',
    dinnerSupportPrice: null,
    createdDateTime: '2023-03-01',
    updatedDateTime: '2023-03-02',
  },
  {
    spotId: 36,
    spotName: 'a29',
    groupId: 1,
    groupName: '달리셔스1',
    zipCode: '12345',
    address1: '서울 강남구 역삼로 168',
    address2: '팁스타운S6',
    location: null,
    diningType: '아침, 점심, 저녁',
    breakfastLastOrderTime: '00:00',
    breakfastDeliveryTime: '00:00',
    breakfastUseDays: '월, 화, 수, 목, 금',
    breakfastSupportPrice: null,
    lunchLastOrderTime: '00:00',
    lunchDeliveryTime: '00:00',
    lunchUseDays: '월, 화, 수, 목, 금',
    lunchSupportPrice: null,
    dinnerLastOrderTime: '00:00',
    dinnerDeliveryTime: '00:00',
    dinnerUseDays: '월, 화, 수, 목, 금',
    dinnerSupportPrice: null,
    createdDateTime: '2023-03-01',
    updatedDateTime: '2023-03-02',
  },
  {
    spotId: 37,
    spotName: 'a30',
    groupId: 1,
    groupName: '달리셔스1',
    zipCode: '12345',
    address1: '서울 강남구 역삼로 168',
    address2: '팁스타운S6',
    location: null,
    diningType: '아침, 점심, 저녁',
    breakfastLastOrderTime: '00:00',
    breakfastDeliveryTime: '00:00',
    breakfastUseDays: '월, 화, 수, 목, 금',
    breakfastSupportPrice: null,
    lunchLastOrderTime: '00:00',
    lunchDeliveryTime: '00:00',
    lunchUseDays: '월, 화, 수, 목, 금',
    lunchSupportPrice: null,
    dinnerLastOrderTime: '00:00',
    dinnerDeliveryTime: '00:00',
    dinnerUseDays: '월, 화, 수, 목, 금',
    dinnerSupportPrice: null,
    createdDateTime: '2023-03-01',
    updatedDateTime: '2023-03-02',
  },
  {
    spotId: 38,
    spotName: 'a31',
    groupId: 1,
    groupName: '달리셔스1',
    zipCode: '12345',
    address1: '서울 강남구 역삼로 168',
    address2: '팁스타운S6',
    location: null,
    diningType: '',
    breakfastLastOrderTime: null,
    breakfastDeliveryTime: null,
    breakfastUseDays: null,
    breakfastSupportPrice: null,
    lunchLastOrderTime: null,
    lunchDeliveryTime: null,
    lunchUseDays: null,
    lunchSupportPrice: null,
    dinnerLastOrderTime: null,
    dinnerDeliveryTime: null,
    dinnerUseDays: null,
    dinnerSupportPrice: null,
    createdDateTime: '2023-03-01',
    updatedDateTime: '2023-03-02',
  },
  {
    spotId: 39,
    spotName: 'a32',
    groupId: 1,
    groupName: '달리셔스1',
    zipCode: '12345',
    address1: '서울 강남구 역삼로 168',
    address2: '팁스타운S6',
    location: null,
    diningType: '아침, 점심, 저녁',
    breakfastLastOrderTime: '00:00',
    breakfastDeliveryTime: '00:00',
    breakfastUseDays: '월, 화, 수, 목, 금',
    breakfastSupportPrice: null,
    lunchLastOrderTime: '00:00',
    lunchDeliveryTime: '00:00',
    lunchUseDays: '월, 화, 수, 목, 금',
    lunchSupportPrice: null,
    dinnerLastOrderTime: '00:00',
    dinnerDeliveryTime: '00:00',
    dinnerUseDays: '월, 화, 수, 목, 금',
    dinnerSupportPrice: null,
    createdDateTime: '2023-03-01',
    updatedDateTime: '2023-03-02',
  },
  {
    spotId: 44,
    spotName: 'a36',
    groupId: 1,
    groupName: '달리셔스1',
    zipCode: '12345',
    address1: '서울 강남구 역삼로 168',
    address2: '팁스타운S6',
    location: null,
    diningType: '아침, 저녁',
    breakfastLastOrderTime: '00:00',
    breakfastDeliveryTime: '08:00',
    breakfastUseDays: '월, 수, 금, 화, 목',
    breakfastSupportPrice: 0,
    lunchLastOrderTime: null,
    lunchDeliveryTime: null,
    lunchUseDays: null,
    lunchSupportPrice: null,
    dinnerLastOrderTime: '15:00',
    dinnerDeliveryTime: '18:30',
    dinnerUseDays: '월, 수, 금, 화, 목',
    dinnerSupportPrice: 7000,
    createdDateTime: '2023-03-01',
    updatedDateTime: '2023-03-03',
  },
  {
    spotId: 45,
    spotName: 'a70',
    groupId: 1,
    groupName: '달리셔스1',
    zipCode: '12345',
    address1: '서울 강남구 역삼로 168',
    address2: '팁스타운S6',
    location: null,
    diningType: '아침, 저녁',
    breakfastLastOrderTime: '00:00',
    breakfastDeliveryTime: '08:00',
    breakfastUseDays: '월, 수, 금, 화, 목',
    breakfastSupportPrice: 5000,
    lunchLastOrderTime: null,
    lunchDeliveryTime: null,
    lunchUseDays: null,
    lunchSupportPrice: null,
    dinnerLastOrderTime: '15:00',
    dinnerDeliveryTime: '18:30',
    dinnerUseDays: '월, 수, 금, 화, 목',
    dinnerSupportPrice: 5000,
    createdDateTime: '2023-03-01',
    updatedDateTime: '2023-03-03',
  },
  {
    spotId: 46,
    spotName: 'a38',
    groupId: 1,
    groupName: '달리셔스1',
    zipCode: '12345',
    address1: '서울 강남구 역삼로 168',
    address2: '팁스타운S6',
    location: null,
    diningType: '아침, 점심, 저녁',
    breakfastLastOrderTime: '00:00',
    breakfastDeliveryTime: '08:00',
    breakfastUseDays: '월,화,수,목,금',
    breakfastSupportPrice: 5000,
    lunchLastOrderTime: '09:00',
    lunchDeliveryTime: '12:00',
    lunchUseDays: '월,화,수,목,금',
    lunchSupportPrice: 5000,
    dinnerLastOrderTime: '15:00',
    dinnerDeliveryTime: '18:00',
    dinnerUseDays: '월,화,수,목,금',
    dinnerSupportPrice: 5000,
    createdDateTime: '2023-03-01',
    updatedDateTime: '2023-03-02',
  },
  {
    spotId: 51,
    spotName: 'a43',
    groupId: 1,
    groupName: '달리셔스1',
    zipCode: '12345',
    address1: '서울 강남구 역삼로 168',
    address2: '팁스타운S6',
    location: null,
    diningType: '아침, 점심, 저녁',
    breakfastLastOrderTime: '00:00',
    breakfastDeliveryTime: '08:00',
    breakfastUseDays: '월,화,수,목,금',
    breakfastSupportPrice: 5000,
    lunchLastOrderTime: '09:00',
    lunchDeliveryTime: '12:00',
    lunchUseDays: '월,화,수,목,금',
    lunchSupportPrice: 5000,
    dinnerLastOrderTime: '15:00',
    dinnerDeliveryTime: '18:00',
    dinnerUseDays: '월,화,수,목,금',
    dinnerSupportPrice: 5000,
    createdDateTime: '2023-03-01',
    updatedDateTime: '2023-03-02',
  },
  {
    spotId: 52,
    spotName: 'a44',
    groupId: 1,
    groupName: '달리셔스1',
    zipCode: '12345',
    address1: '서울 강남구 역삼로 168',
    address2: '팁스타운S6',
    location: null,
    diningType: '아침, 점심',
    breakfastLastOrderTime: '09:00',
    breakfastDeliveryTime: '09:00',
    breakfastUseDays: '월,화,수,목,금',
    breakfastSupportPrice: null,
    lunchLastOrderTime: '09:00',
    lunchDeliveryTime: '09:00',
    lunchUseDays: '월,화,수,목,금',
    lunchSupportPrice: null,
    dinnerLastOrderTime: null,
    dinnerDeliveryTime: null,
    dinnerUseDays: null,
    dinnerSupportPrice: null,
    createdDateTime: '2023-03-02',
    updatedDateTime: '2023-03-02',
  },
  {
    spotId: 91,
    spotName: 'a45',
    groupId: 11,
    groupName: '밀당PT 여의도1',
    zipCode: '7335',
    address1: '서울특별시 영등포구 여의대로 108',
    address2: '파크원',
    location: null,
    diningType: '아침',
    breakfastLastOrderTime: '00:00',
    breakfastDeliveryTime: '07:00',
    breakfastUseDays: '월, 화, 수, 목, 금',
    breakfastSupportPrice: null,
    lunchLastOrderTime: null,
    lunchDeliveryTime: null,
    lunchUseDays: null,
    lunchSupportPrice: null,
    dinnerLastOrderTime: null,
    dinnerDeliveryTime: null,
    dinnerUseDays: null,
    dinnerSupportPrice: null,
    createdDateTime: '2023-03-02',
    updatedDateTime: '2023-03-02',
  },
  {
    spotId: 92,
    spotName: 'a46',
    groupId: 12,
    groupName: '밀당PT 여의도2',
    zipCode: '7335',
    address1: '서울특별시 영등포구 여의대로 108',
    address2: '파크원',
    location: null,
    diningType: '아침',
    breakfastLastOrderTime: '00:00',
    breakfastDeliveryTime: '07:00',
    breakfastUseDays: '월, 화, 수, 목, 금',
    breakfastSupportPrice: 500,
    lunchLastOrderTime: null,
    lunchDeliveryTime: null,
    lunchUseDays: null,
    lunchSupportPrice: null,
    dinnerLastOrderTime: null,
    dinnerDeliveryTime: null,
    dinnerUseDays: null,
    dinnerSupportPrice: null,
    createdDateTime: '2023-03-02',
    updatedDateTime: '2023-03-02',
  },
  {
    spotId: 93,
    spotName: 'a47',
    groupId: 13,
    groupName: '위시티자이아파트',
    zipCode: '10323',
    address1: '경기도 고양시 일산동구 식사동',
    address2: '위시티 4로 45',
    location: null,
    diningType: '아침',
    breakfastLastOrderTime: '00:00',
    breakfastDeliveryTime: '07:00',
    breakfastUseDays: '월, 화, 수, 목, 금',
    breakfastSupportPrice: 0,
    lunchLastOrderTime: null,
    lunchDeliveryTime: null,
    lunchUseDays: null,
    lunchSupportPrice: null,
    dinnerLastOrderTime: null,
    dinnerDeliveryTime: null,
    dinnerUseDays: null,
    dinnerSupportPrice: null,
    createdDateTime: '2023-03-02',
    updatedDateTime: '2023-03-02',
  },
  {
    spotId: 94,
    spotName: 'a48',
    groupId: 14,
    groupName: '밀당PT 여의도1',
    zipCode: '7335',
    address1: '서울특별시 영등포구 여의대로 108',
    address2: '파크원',
    location: null,
    diningType: '아침',
    breakfastLastOrderTime: '00:00',
    breakfastDeliveryTime: '07:00',
    breakfastUseDays: '월, 화, 수, 목, 금',
    breakfastSupportPrice: 0,
    lunchLastOrderTime: null,
    lunchDeliveryTime: null,
    lunchUseDays: null,
    lunchSupportPrice: null,
    dinnerLastOrderTime: null,
    dinnerDeliveryTime: null,
    dinnerUseDays: null,
    dinnerSupportPrice: null,
    createdDateTime: '2023-03-02',
    updatedDateTime: '2023-03-02',
  },
  {
    spotId: 100,
    spotName: '상경빌딩 2층',
    groupId: 1,
    groupName: '달리셔스1',
    zipCode: '12345',
    address1: '서울 강남구 역삼로 168',
    address2: '팁스타운S6',
    location: null,
    diningType: '아침, 저녁',
    breakfastLastOrderTime: '00:00',
    breakfastDeliveryTime: '08:00',
    breakfastUseDays: '월, 수, 금, 화, 목',
    breakfastSupportPrice: 5000,
    lunchLastOrderTime: null,
    lunchDeliveryTime: null,
    lunchUseDays: null,
    lunchSupportPrice: null,
    dinnerLastOrderTime: '15:00',
    dinnerDeliveryTime: '18:00',
    dinnerUseDays: '월, 수, 금, 화, 목',
    dinnerSupportPrice: 7000,
    createdDateTime: '2023-03-02',
    updatedDateTime: '2023-03-02',
  },
];

address1: '서울특별시 영등포구 여의대로 108';
address2: '파크원';
breakfastDeliveryTime: '07:00';
breakfastLastOrderTime: '00:00';
breakfastSupportPrice: null;
breakfastUseDays: '월, 화, 수, 목, 금';
createdDateTime: '2023-03-02';
diningType: '아침';
dinnerDeliveryTime: null;
dinnerLastOrderTime: null;
dinnerSupportPrice: null;
dinnerUseDays: null;
groupId: 11;
groupName: '밀당PT 여의도1';
location: null;
lunchDeliveryTime: null;
lunchLastOrderTime: null;
lunchSupportPrice: null;
lunchUseDays: null;
spotId: 91;
spotName: 'a45';
updatedDateTime: '2023-03-02';
zipCode: '7335';

address1: '서울특별시 영등포구 여의대로 108';
address2: '파크원';
breakfastDeliveryTime: '07:00';
breakfastLastOrderTime: '00:00';
breakfastSupportPrice: 500;
breakfastUseDays: '월, 화, 수, 목, 금';
createdDateTime: '2023-03-02';
diningType: '아침';
dinnerDeliveryTime: null;
dinnerLastOrderTime: null;
dinnerSupportPrice: null;
dinnerUseDays: null;
groupId: 12;
groupName: '밀당PT 여의도2';
location: null;
lunchDeliveryTime: null;
lunchLastOrderTime: null;
lunchSupportPrice: null;
lunchUseDays: null;
spotId: 92;
spotName: 'a46';
updatedDateTime: '2023-03-02';
zipCode: '7335';
