export const SpotInfoFieldsToOpen = {
  // id: '아이디',
  clientGroupName: '그룹이름',
  clientGroupId: '그룹아이디',
  name: '스팟이름',
  spotId: '스팟아이디',
  zipCode: '우편번호',
  addressDepth1: '기본주소',
  addressDepth2: '상세주소',
  location: '위치',
  diningTypes: '식타입',
  breakfastDeliveryTime: '배송시아침',
  breakfastEmbUseDays: '주문요아침',
  breakfastDailySupportPrice: '지원아침',
  lunchDeliveryTime: '배송시간점심',
  lunchEmbUseDays: '주문요일점심',
  lunchDailySupportPrice: '지원금점심',
  dinnerDeliveryTime: '배송시간저녁',
  dinnerEmbUseDays: '주문요일저녁',
  dinnerDailySupportPrice: '지원금저녁',
  createDateTime: '생성일',
  updatedDateTime: '수정일',
};

export const SpotInfoFieldsData = [
  //   {
  //     fieldName: 'id',
  //     fieldNameKor: '아이디',
  //     placeholder: '예:아이디',
  //     maxCharLength: 20,
  //     flex: 1,
  //     width: undefined,
  //   },
  {
    fieldName: 'clientGroupName',
    fieldNameKor: '그룹 이름',
    placeholder: '',
    maxCharLength: 20,
    flex: 1,
    width: undefined,
  },
  {
    fieldName: 'clientGroupId',
    fieldNameKor: '그룹 아이디',
    placeholder: '',
    maxCharLength: 20,
    flex: 1,
    width: undefined,
  },
  {
    fieldName: 'name',
    fieldNameKor: '스팟이름',
    placeholder: '',
    maxCharLength: 20,
    flex: 1,
    width: undefined,
  },
  {
    fieldName: 'spotId',
    fieldNameKor: '스팟아이디',
    placeholder: '',
    maxCharLength: 20,
    flex: 1,
    width: undefined,
  },
  {
    fieldName: 'zipCode',
    fieldNameKor: '우편번호',
    placeholder: '',
    maxCharLength: 20,
    flex: 1,
    width: undefined,
  },
  {
    fieldName: 'addressDepth1',
    fieldNameKor: '기본주소',
    placeholder: '',
    maxCharLength: 20,
    flex: 1,
    width: undefined,
  },
  {
    fieldName: 'addressDepth2',
    fieldNameKor: '상세주소',
    placeholder: '',
    maxCharLength: 20,
    flex: 1,
    width: undefined,
  },
  {
    fieldName: 'location',
    fieldNameKor: '위치',
    placeholder: '',
    maxCharLength: 20,
    flex: 1,
    width: undefined,
  },
  {
    fieldName: 'diningTypes',
    fieldNameKor: '식타입',
    placeholder: '',
    maxCharLength: 20,
    flex: 1,
    width: undefined,
  },
  {
    fieldName: 'breakfastDeliveryTime',
    fieldNameKor: '배송시아침',
    placeholder: '',
    maxCharLength: 20,
    flex: 1,
    width: undefined,
  },
  {
    fieldName: 'breakfastEmbUseDays',
    fieldNameKor: '주문요아침',
    placeholder: '',
    maxCharLength: 20,
    flex: 1,
    width: undefined,
  },
  {
    fieldName: 'breakfastDailySupportPrice',
    fieldNameKor: '지원 아침',
    placeholder: '',
    maxCharLength: 20,
    flex: 1,
    width: undefined,
  },
  {
    fieldName: 'lunchDeliveryTime',
    fieldNameKor: '배송시간 점심',
    placeholder: '',
    maxCharLength: 20,
    flex: 1,
    width: undefined,
  },
  {
    fieldName: 'lunchEmbUseDays',
    fieldNameKor: '주문요일 점심',
    placeholder: '',
    maxCharLength: 20,
    flex: 1,
    width: undefined,
  },
  {
    fieldName: 'lunchDailySupportPrice',
    fieldNameKor: '지원금 점심',
    placeholder: '',
    maxCharLength: 20,
    flex: 1,
    width: undefined,
  },
  {
    fieldName: 'dinnerDeliveryTime',
    fieldNameKor: '배송시간 저녁',
    placeholder: '',
    maxCharLength: 20,
    flex: 1,
    width: undefined,
  },
  {
    fieldName: 'dinnerEmbUseDays',
    fieldNameKor: '주문요일 저녁',
    placeholder: '',
    maxCharLength: 20,
    flex: 1,
    width: undefined,
  },
  {
    fieldName: 'dinnerDailySupportPrice',
    fieldNameKor: '지원금 저녁',
    placeholder: '',
    maxCharLength: 20,
    flex: 1,
    width: undefined,
  },
  {
    fieldName: 'createDateTime',
    fieldNameKor: '생성일',
    placeholder: '',
    maxCharLength: 20,
    flex: 1,
    width: undefined,
  },
  {
    fieldName: 'updatedDateTime',
    fieldNameKor: '수정일',
    placeholder: '',
    maxCharLength: 20,
    flex: 1,
    width: undefined,
  },
];
