export const SpotInfoFieldsToOpen = {
  // id: '아이디',
  groupId: '그룹아이디',
  groupName: '그룹이름',
  spotId: '스팟아이디',
  spotName: '스팟이름',
  zipCode: '우편번호',
  address1: '기본주소',
  address2: '상세주소',
  location: '위치',
  breakfastDeliveryTime: '배송시아침',
  breakfastSupportPrice: '지원아침',
  breakfastUseDays: '주문요일아침',
  lunchDeliveryTime: '배송시간점심',
  lunchSupportPrice: '지원금점심',
  lunchUseDays: '주문요일점심',
  dinnerDeliveryTime: '배송시간저녁',
  dinnerSupportPrice: '지원금저녁',
  dinnerUseDays: '주문요일저녁',
  createdDateTime: '생성일',
  lastOrderTime: '주문마감시간',
  updatedDateTime: '수정일',
  // diningType: '식타입',
};

export const SpotInfoFieldsData = [
  {
    fieldName: 'groupId',
    fieldNameKor: '그룹아이디',
    placeholder: '',
    maxCharLength: 40,
    flex: 1,
    width: undefined,
  },
  {
    fieldName: 'groupName',
    fieldNameKor: '그룹이름',
    placeholder: '',
    maxCharLength: 40,
    flex: 1,
    width: undefined,
  },
  {
    fieldName: 'spotId',
    fieldNameKor: '스팟아이디',
    placeholder: '',
    maxCharLength: 40,
    flex: 1,
    width: undefined,
  },
  {
    fieldName: 'spotName',
    fieldNameKor: '스팟이름',
    placeholder: '',
    maxCharLength: 40,
    flex: 1,
    width: undefined,
  },
  {
    fieldName: 'zipCode',
    fieldNameKor: '우편번호',
    placeholder: '',
    maxCharLength: 40,
    flex: 1,
    width: undefined,
  },
  {
    fieldName: 'address1',
    fieldNameKor: '기본주소',
    placeholder: '',
    maxCharLength: 40,
    flex: 1,
    width: undefined,
  },
  {
    fieldName: 'address2',
    fieldNameKor: '상세주소',
    placeholder: '',
    maxCharLength: 40,
    flex: 1,
    width: undefined,
  },
  {
    fieldName: 'location',
    fieldNameKor: '위치',
    placeholder: '',
    maxCharLength: 40,
    flex: 1,
    width: undefined,
  },
  {
    fieldName: 'breakfastDeliveryTime',
    fieldNameKor: '배송시아침',
    placeholder: '',
    maxCharLength: 40,
    flex: 1,
    width: undefined,
  },
  {
    fieldName: 'breakfastSupportPrice',
    fieldNameKor: '지원아침',
    placeholder: '',
    maxCharLength: 40,
    flex: 1,
    width: undefined,
  },
  {
    fieldName: 'breakfastUseDays',
    fieldNameKor: '주문요일아침',
    placeholder: '',
    maxCharLength: 40,
    flex: 1,
    width: undefined,
  },
  {
    fieldName: 'lunchDeliveryTime',
    fieldNameKor: '배송시간점심',
    placeholder: '',
    maxCharLength: 40,
    flex: 1,
    width: undefined,
  },
  {
    fieldName: 'lunchSupportPrice',
    fieldNameKor: '지원금점심',
    placeholder: '',
    maxCharLength: 40,
    flex: 1,
    width: undefined,
  },
  {
    fieldName: 'lunchUseDays',
    fieldNameKor: '주문요일점심',
    placeholder: '',
    maxCharLength: 40,
    flex: 1,
    width: undefined,
  },
  {
    fieldName: 'dinnerDeliveryTime',
    fieldNameKor: '배송시간저녁',
    placeholder: '',
    maxCharLength: 40,
    flex: 1,
    width: undefined,
  },
  {
    fieldName: 'dinnerSupportPrice',
    fieldNameKor: '지원금저녁',
    placeholder: '',
    maxCharLength: 40,
    flex: 1,
    width: undefined,
  },
  {
    fieldName: 'dinnerUseDays',
    fieldNameKor: '주문요일저녁',
    placeholder: '',
    maxCharLength: 40,
    flex: 1,
    width: undefined,
  },
  {
    fieldName: 'createdDateTime',
    fieldNameKor: '생성일',
    placeholder: '',
    maxCharLength: 40,
    flex: 1,
    width: undefined,
  },
  {
    fieldName: 'lastOrderTime',
    fieldNameKor: '주문마감시간',
    placeholder: '',
    maxCharLength: 40,
    flex: 1,
    width: undefined,
  },
  {
    fieldName: 'updatedDateTime',
    fieldNameKor: '수정일',
    placeholder: '',
    maxCharLength: 40,
    flex: 1,
    width: undefined,
  },
];
