// "spotId": 1,
//             "spotName": "a1",
//             "groupId": 1,
//             "groupName": "달리셔스",
//             "zipCode": "12345",
//             "address1": null,
//             "address2": null,
//             "location": null,
//             "diningType": "아침, 점심, 저녁",
//             "breakfastLastOrderTime": "00:00",
//             "breakfastDeliveryTime": "08:00",
//             "breakfastUseDays": "월, 수, 금, 화, 목",
//             "breakfastSupportPrice": 5000,
//             "lunchLastOrderTime": null,
//             "lunchDeliveryTime": null,
//             "lunchUseDays": null,
//             "lunchSupportPrice": null,
//             "dinnerLastOrderTime": null,
//             "dinnerDeliveryTime": null,
//             "dinnerUseDays": null,
//             "dinnerSupportPrice": null,
//             "createdDateTime": null,
//             "updatedDateTime": null,
//             "status": 1
