export const CustomerFieldsToOpen = {
  userId: '아이디',
  password: '비밀번호',
  userName: '사용자 명',
  role: '유저타입(0: 일반, 1: 관리자)',
  phone: '폰 번호',
  email: '이메일',
  groupName: '그룹이름',
  point: '보유 포인트',
  gourmetType: '미식가 타입',
  isMembership: '멤버십 여부',
  userEmailAgreed: '이메일 동의여부',
  userEmailAgreedDateTime: '이메일 동의 / 철회 날짜',
  userOrderAlarm: '주문 알림',
  recentLoginDateTime: '마지막 로그인 날짜',
  userCreatedDateTime: '생성일',
  userUpdatedDateTime: '수정일',
  generalEmail: '일반기업_이메일',
  kakaoEmail: '카카오_이메일',
  naverEmail: '네이버_이메일',
  facebookEmail: '페이스북_이메일',
  appleEmail: '애플_이메일',
};

export const CustomerFieldsData = [
  {
    userId: 'num',
    password: 'str',
    userName: 'str',
    role: 'str',
    phone: 'str',
    email: 'str',
    groupName: 'str',
    point: 'num',
    gourmetType: 'str',
    isMembership: 'Boolean',
    userEmailAgreed: 'str',
    userEmailAgreedDateTime: 'str',
    userOrderAlarm: 'str',
    recentLoginDateTime: 'str',
    userCreatedDateTime: 'str',
    userUpdatedDateTime: 'str',
    generalEmail: 'str',
    kakaoEmail: 'str',
    naverEmail: 'str',
    facebookEmail: 'str',
    appleEmail: 'str',
  },
  {
    userId: 'num2',
    password: 'str',
    userName: 'str',
    role: 'str',
    phone: 'str',
    email: 'str',
    groupName: 'str',
    point: 'num',
    gourmetType: 'str',
    isMembership: 'Boolean',
    userEmailAgreed: 'str',
    userEmailAgreedDateTime: 'str',
    userOrderAlarm: 'str',
    recentLoginDateTime: 'str',
    userCreatedDateTime: 'str',
    userUpdatedDateTime: 'str',
    generalEmail: 'str',
    kakaoEmail: 'str',
    naverEmail: 'str',
    facebookEmail: 'str',
    appleEmail: 'str',
  },
];
