import {orderApis} from 'api/order';
import {successApi} from 'api/success';
import axios from 'axios';
import React, {useEffect} from 'react';
import {useParams, useSearchParams} from 'react-router-dom';
import {PageWrapper} from '../style/common.style';

const Success = () => {
  const [searchParams, setSearchParams] = useSearchParams();

  useEffect(() => {
    const req = {
      paymentKey: searchParams.get('paymentKey'),
      orderId: searchParams.get('orderId'),
      amount: Number(searchParams.get('amount')),
      orderItems: JSON.parse(searchParams.get('orderItems')),
    };
    const callOrder = async () => {
      const res = await axios.post('/users/me/orders', {
        ...req,
      });
      // const res = await successApi.orderSuccess(req);
      window.ReactNativeWebView.postMessage(
        JSON.stringify({...res, type: 'NOMAL'}),
      );
    };
    try {
      callOrder();
    } catch ({request, status, error}) {
      alert(
        'code:' +
          status +
          '\n' +
          'message:' +
          JSON.stringify(request) +
          '\n' +
          'error:' +
          error,
      );
    }
  }, [searchParams]);
  return <PageWrapper>결제 승인중...</PageWrapper>;
};

export default Success;

const data = [
  {
    password: '$2a$10$cDoyvitueYh8rPTkbjsB2uFXP5OzIM1fHrRr9ibi7zYK9e7ZW4mOG',
    name: '김민지',
    email: 'qw382@naver.com',
    phone: null,
    role: '일반',
    status: 1,
    groupName: '달리셔스, 위시티자이아파트, 밀당PT 여의도',
    point: 0,
    marketingAgree: null,
    marketingAlarm: true,
    orderAlarm: null,
  },
  {
    password: '$2a$10$TKTDPB6WZnUFLdMlR6su.eDO8qYDe8UyE52V0C7IDZp621/ijUDZu',
    name: '장경태',
    email: 'zxs3710@naver.com',
    phone: '01036435850',
    role: '일반',
    status: 1,
    groupName: '달리셔스, 위시티자이아파트',
    point: 0,
    marketingAgree: null,
    marketingAlarm: true,
    orderAlarm: null,
  },
  {
    password: '1234',
    name: '장경태',
    email: 'zxsxz123@dreamwiz.com',
    phone: '01036435850',
    role: '일반',
    status: 1,
    groupName: '위시티자이아파트, 달리셔스, 밀당PT 여의도',
    point: 3000,
    marketingAgree: null,
    marketingAlarm: null,
    orderAlarm: null,
  },
  {
    password: '$2a$10$DhcZXvUb/gc2/Fm14i2J2.T9MGoojxSpl1SUuDAixE8bVHXni8mxy',
    name: '강지성',
    email: 'wltjd1484@naver.com',
    phone: '01022214632',
    role: '일반',
    status: 1,
    groupName: '위시티자이아파트, 달리셔스',
    point: 0,
    marketingAgree: null,
    marketingAlarm: null,
    orderAlarm: null,
  },
  {
    password: '$2a$10$h9Lqwnt68xqJSsLI4r9O6u8B/tquhe3HUnot13MSVhbVoU5WSeVpm',
    name: '조센징',
    email: 'hg9822@naver.com',
    phone: '01037747293',
    role: '일반',
    status: 1,
    groupName: '달리셔스',
    point: 0,
    marketingAgree: null,
    marketingAlarm: null,
    orderAlarm: null,
  },
  {
    password: '$2a$10$Ca68VgmIuGG2vlNsKMCGBuIT.xigq9XfQqKnmIhcxaIX2BPsdD21m',
    name: '이강용',
    email: 'ceo_kangyong.lee@cookingfactory.co.kr',
    phone: '01097412388',
    role: '일반',
    status: 1,
    groupName: '없음',
    point: 0,
    marketingAgree: null,
    marketingAlarm: null,
    orderAlarm: null,
  },
  {
    password: '$2a$10$IFg4D2i93AK3pC0llXzbPeYM3pX4H90v1/.pSrsnaPES.vDVl2rvK',
    name: '이름없음',
    email: 'k5fd82hqbn@privaterelay.appleid.com',
    phone: '-',
    role: '일반',
    status: 1,
    groupName: '없음',
    point: 0,
    marketingAgree: null,
    marketingAlarm: null,
    orderAlarm: null,
  },
  {
    password: '$2a$10$vHzFvfIvQDw/bz.mW2ztg.ZrmbHZJlwAWU8Xjn/hLjBHykdYfjZty',
    name: '이름',
    email: 'lilomeowlilo@gmail.com',
    phone: '01022222222',
    role: '일반',
    status: 1,
    groupName: '달리셔스',
    point: 0,
    marketingAgree: null,
    marketingAlarm: null,
    orderAlarm: null,
  },
  {
    password: '$2a$10$rLCjkfxq.q3c9ppXk.tFQOWR05pAkMD9dIk6gURNTzZh0l5qEP7aC',
    name: '테스트',
    email: 'dalicious.test@gmail.com',
    phone: '01094576119',
    role: '일반',
    status: 1,
    groupName: '위시티자이아파트',
    point: 0,
    marketingAgree: null,
    marketingAlarm: true,
    orderAlarm: null,
  },
  {
    password: '$2a$10$36M/0UkqpLwdq1avN/TiYeRvnC2NHSm1r1HU2QTXK3KThs4UQveMi',
    name: '김지혜',
    email: 'kjeehye03@gmail.com',
    phone: '-',
    role: '일반',
    status: 1,
    groupName: '위시티자이아파트',
    point: 0,
    marketingAgree: null,
    marketingAlarm: null,
    orderAlarm: null,
  },
  {
    password: '$2a$10$xKWWZT4n85sPItOIgNdK8e.4.FFeyJoZrCR0YQDeXxd.etShZbKA2',
    name: '남태호',
    email: 'han127kr@naver.com',
    phone: '01086000847',
    role: '일반',
    status: 1,
    groupName: '위시티자이아파트',
    point: 0,
    marketingAgree: null,
    marketingAlarm: true,
    orderAlarm: null,
  },
  {
    password: '$2a$10$MdrLro8JCeXHoM5ackOvSuyVEd/EKjeCEP7MhR6gzLNQn1n8orsj6',
    name: '남태호',
    email: 'han127kr@dalicious.co',
    phone: '01086000847',
    role: '일반',
    status: 1,
    groupName: '달리셔스',
    point: 0,
    marketingAgree: null,
    marketingAlarm: true,
    orderAlarm: null,
  },
  {
    password: '$2a$10$O0xt8Ig9tsFIdNxyG6q11.dWoLFaNl50FP8bkJuBpM6uw9r1K.Wzm',
    name: '전정호',
    email: 'calseolralria@nate.com',
    phone: '010-0000-0000',
    role: '일반',
    status: 1,
    groupName: '위시티자이아파트, 밀당PT 여의도',
    point: 0,
    marketingAgree: null,
    marketingAlarm: null,
    orderAlarm: null,
  },
  {
    password: '$2a$10$GDPxZkYstBBpQDZ9TlmQsOhpeaAmhEsN.88FwvAaeiUKh3X1p5ruy',
    name: '이름없음',
    email: 'vgq67ptyr6@privaterelay.appleid.com',
    phone: '-',
    role: '일반',
    status: 1,
    groupName: '없음',
    point: 0,
    marketingAgree: null,
    marketingAlarm: null,
    orderAlarm: null,
  },
  {
    password: '$2a$10$JIrOBFrjQqi8s0wnFrhfVup3w8o3UPF0KCC81tomDIlBFgfh4XIRK',
    name: '이강용',
    email: 'ajkb23@gmail.com',
    phone: '01097412388',
    role: '일반',
    status: 1,
    groupName: '위시티자이아파트',
    point: 0,
    marketingAgree: null,
    marketingAlarm: null,
    orderAlarm: null,
  },
  {
    password: '$2a$10$VJpNqo0aSH1UKMbWEJkFK.JRjfM284/mRDDXonM3FQn6rPxldZjbe',
    name: '조재신',
    email: 'jaesin.cho@dalicious.co',
    phone: '01029521190',
    role: '일반',
    status: 1,
    groupName: '위시티자이아파트',
    point: 0,
    marketingAgree: null,
    marketingAlarm: true,
    orderAlarm: null,
  },
  {
    password: '$2a$10$IJNLomJlbDoNfy9ntCUd..PZ6zUmxjNMaJaNvswLStlx2r5iGT.Ba',
    name: '모름',
    email: 'newappreview2020@gmail.com',
    phone: '-',
    role: '일반',
    status: 1,
    groupName: '없음',
    point: 0,
    marketingAgree: null,
    marketingAlarm: null,
    orderAlarm: null,
  },
  {
    password: '$2a$10$PDvdzTWyXgi76zeVqyywleX6eoBslEufbOJDKqG9dW9BtKCqFo2ZW',
    name: '깜찍이',
    email: 'kkamjikicool@daum.net',
    phone: '01087846417',
    role: '일반',
    status: 1,
    groupName: '위시티자이아파트',
    point: 0,
    marketingAgree: null,
    marketingAlarm: null,
    orderAlarm: null,
  },
  {
    password: '$2a$10$bPjFRzUGkOQ52OSiijsN8evakF/hvrOH72HL0ytVneyv8G5n2P9ZO',
    name: '이상진',
    email: 'lkokk2@nate.com',
    phone: '01077060226',
    role: '일반',
    status: 1,
    groupName: '위시티자이아파트',
    point: 0,
    marketingAgree: null,
    marketingAlarm: null,
    orderAlarm: null,
  },
  {
    password: '$2a$10$KFL214PET5NZjjrQee9xsuQ0DFq.zMDBLJ/3tQ05qeq.ccTFmQ88y',
    name: 'NuageLaboratoire',
    email: 'VCFUO3LXGNL4NDLUEDDDO773XY-00@cloudtestlabaccounts.com',
    phone: null,
    role: '일반',
    status: 1,
    groupName: '없음',
    point: 0,
    marketingAgree: null,
    marketingAlarm: null,
    orderAlarm: null,
  },
  {
    password: '$2a$10$4UXLeGdzoLIjXnphFGRDAepNb6r3AMU/2jCyetgdkZaxctp06vqwy',
    name: '송재의(JaySong)',
    email: 'jake000120@gmail.com',
    phone: null,
    role: '일반',
    status: 1,
    groupName: '위시티자이아파트',
    point: 0,
    marketingAgree: null,
    marketingAlarm: null,
    orderAlarm: null,
  },
  {
    password: '$2a$10$yanpgE6zwxSYMm95r1itpu1f3yK8ziyHTuqrZoTHZz6K0IY.oC1e2',
    name: '양희정',
    email: 'sweetieade@naver.com',
    phone: '01066019103',
    role: '일반',
    status: 1,
    groupName: '없음',
    point: 0,
    marketingAgree: null,
    marketingAlarm: null,
    orderAlarm: null,
  },
  {
    password: '$2a$10$96I6Wl4DDN.iKx4MJCuCO.fXNxPHcMcN3GpK7VYYii2LLMDzr0AnC',
    name: '정석원',
    email: 'standardwon@naver.com',
    phone: '01028763033',
    role: '일반',
    status: 1,
    groupName: '없음',
    point: 0,
    marketingAgree: null,
    marketingAlarm: null,
    orderAlarm: null,
  },
  {
    password: '$2a$10$1qICH5ipv/Y5EkqrL2pB2.2xg5whYpZA0Q5ZpdSjJFeSuIV9sGlSq',
    name: '이름없음',
    email: 'mqqj7sdwzp@privaterelay.appleid.com',
    phone: null,
    role: '일반',
    status: 2,
    groupName: '없음',
    point: 0,
    marketingAgree: null,
    marketingAlarm: null,
    orderAlarm: null,
  },
  {
    password: '$2a$10$awYntxtIKjfkXTV/CQVIWOFon7x1h.lkEvC1GCJroxzY5EmrE/SW6',
    name: '이름없음',
    email: 'jee-h@hanmail.net',
    phone: null,
    role: '일반',
    status: 1,
    groupName: '없음',
    point: 0,
    marketingAgree: null,
    marketingAlarm: null,
    orderAlarm: null,
  },
  {
    password: '$2a$10$MjmEGnKO7WuQdaNryBkOs.xSyR9BI4s7mqiE85KKPpDL30WuPBOpi',
    name: '김민지2',
    email: '333@3333',
    phone: '01012341234',
    role: 'ADMIN',
    status: 1,
    groupName: '달리셔스, 밀당PT 여의도',
    point: 0,
    marketingAgree: null,
    marketingAlarm: null,
    orderAlarm: null,
  },
  {
    password: '$2a$10$MWVg1h3HnNwgNL6bwp3E9O.WLHFZjL/oejRzNzzU3tWecD3N1WVRe',
    name: '전정호',
    email: 'jeongho.jeo2n@dalicious.co',
    phone: null,
    role: '일반',
    status: 1,
    groupName: '없음',
    point: 0,
    marketingAgree: null,
    marketingAlarm: null,
    orderAlarm: null,
  },
  {
    password: '$2a$10$fym2StJYEWs9HMErZnNShOvzNadLGE.u.jQ6cMucfmPVcie/7uUie',
    name: '전정호',
    email: 'jeongho.jeon@dalicious.co',
    phone: null,
    role: '일반',
    status: 1,
    groupName: '없음',
    point: 0,
    marketingAgree: null,
    marketingAlarm: null,
    orderAlarm: null,
  },
  {
    password: '$2a$10$Q2BF3ltKs2QPIe8YkDpFFOUzdUqWHFeLjq1zXADxkHxrK0jjJA.KK',
    name: '전정호2',
    email: 'jeongho.jeon2@dalicious.co',
    phone: null,
    role: '일반',
    status: 1,
    groupName: '없음',
    point: 0,
    marketingAgree: null,
    marketingAlarm: null,
    orderAlarm: null,
  },
  {
    password: '$2a$10$QjunDkP9I6BZe/4QJEmTReaGYYW3PUGujHRQoxKokai1VX5j3WuH.',
    name: '전정호3',
    email: 'jeongho.jeon3@dalicious.co',
    phone: null,
    role: '일반',
    status: 1,
    groupName: '없음',
    point: 0,
    marketingAgree: null,
    marketingAlarm: null,
    orderAlarm: null,
  },
  {
    password: '$2a$10$UUXjlUSO0ekY6NI4u6XXk.1w6t1x9Ho9ZkVtNCV3wzlDb.2J/ajhG',
    name: '전정호4',
    email: 'jeongho.jeon4@dalicious.co',
    phone: null,
    role: '일반',
    status: 1,
    groupName: '없음',
    point: 0,
    marketingAgree: null,
    marketingAlarm: null,
    orderAlarm: null,
  },
];
